limit_submissions: -1
required_files: 
  - p1.cpp
  - p1.h
  - p2.cpp
  - p2.h
  - p3.cpp
  - p3.h
  - p4.cpp
  - p4.h
  - p5.cpp
  - p5.h
  - p6.cpp
  - p6.h
  - p7.cpp
  - p7.h
  - p8.cpp
  - p8.h
  - p9.cpp
  - p9.h